export default {
  "login": "anon-pradip",
  "id": 27019402,
  "node_id": "MDQ6VXNlcjI3MDE5NDAy",
  "avatar_url": "https://avatars.githubusercontent.com/u/27019402?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/anon-pradip",
  "html_url": "https://github.com/anon-pradip",
  "followers_url": "https://api.github.com/users/anon-pradip/followers",
  "following_url": "https://api.github.com/users/anon-pradip/following{/other_user}",
  "gists_url": "https://api.github.com/users/anon-pradip/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/anon-pradip/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/anon-pradip/subscriptions",
  "organizations_url": "https://api.github.com/users/anon-pradip/orgs",
  "repos_url": "https://api.github.com/users/anon-pradip/repos",
  "events_url": "https://api.github.com/users/anon-pradip/events{/privacy}",
  "received_events_url": "https://api.github.com/users/anon-pradip/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Pradip Subedi",
  "company": "Indreni IT Company",
  "blog": "www.pradip.com",
  "location": " Pokhara, Nepal",
  "email": null,
  "hireable": null,
  "bio": "I am an enthusiastic full-stack web developer plus a team player who approaches challenges with creative solutions.",
  "twitter_username": "@anon_pradip",
  "public_repos": 3,
  "public_gists": 0,
  "followers": 1,
  "following": 3,
  "created_at": "2017-04-07T16:14:05Z",
  "updated_at": "2022-10-11T17:36:12Z"
};